version: '3.8'

services:
  kdb-manager:
    image: gridone.net/kdb-manager:1.2
    container_name: kdb-manager-container
    #ports:
    #  - 28101:28101
    working_dir: /app    
    volumes:
      - /home/gridone/software/kdhc/dev/envs/kdb-manager/.env:/app/.env:Z
      - /home/gridone/software/kdhc/dev/data/kdb-manager/models:/app/models:Z
      - /home/gridone/software/kdhc/dev/logs/kdb-manager:/app/logs:Z
    restart: unless-stopped
    network_mode: host
    deploy: # <--- 이 블록을 추가하세요
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]
    command: "uvicorn kdb_manager:app --port 28101 --host 0.0.0.0 --workers 4 --env-file .env"
